version: '3.6'

services:
  postgres:
    image: postgres
    container_name: store
    restart: always
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
